### PR TITLE
HTTPX async node

### PR DESCRIPTION
**Pull request by b4sus**
Follow up of the issue https://github.com/elastic/elastic-transport-python/issues/95.

Please, pay attention to the verify/cert configuration, this is something I am not very familiar with nor could I test it.

Things to check:

- [x] verify/cert configuration
- [x] headers

### CODE REVIEW

**Comment by pquentin** [comment]
@b4sus Wow, this is exciting! Thanks for working on this.

I'd like to set the expectations here by noting that this is a large change that will require multiple rounds of review, and that I will be slow because of the holidays season coming up. My goal is to have this merged by the end of January.

I haven't looked at the code in any meaningful way but I noticed it uses `asyncio`. However, I'd like to use `anyio` instead because it will get us Trio support for free, which is the main reason to support HTTPX for me.

Also, can you please sign the CLA?

Thanks again!

**Comment by pquentin** [comment]
The `DefaultType | (float | None)` syntax is only valid in Python 3.10 and above, unless you add `from __future__ import annotations`. But if we do that, we should do it in all files, by adding `add_imports = "from __future__ import annotations"` to our isort configuration here: https://github.com/elastic/elastic-transport-python/blob/main/setup.cfg and running pyupgrade. As an added bonus, this sounds like a nice way to get your first contribution in, so that I don't have to click "Approve and run" every time you make a change. (Maybe I can tinker with the GitHub settings to avoid that though.)

The other option is to stick to `typing.Union`.

**Comment by pquentin** [comment]
Are you OK if I submit some small changes to this branch myself?

**Comment by b4sus** [comment]
Of course, go for it.

**Comment by pquentin** [comment]
Could not help myself, this is turning into bigger changes. Hope that's still OK :see_no_evil:

**Pull request merged**
