### PR TITLE
docstring edits for `perform_request`

### PR DESCRIPTION
**Pull request by orrefailaT**

### CODE REVIEW

**Comment by pquentin** [comment]
@orrefailaT Any issues with signing the CLA?

**Comment by orrefailaT** [comment]
@pquentin Not that I can see on my end. I just tried filling it out again to be sure.

**Comment by pquentin** [comment]
@orrefailaT I confirmed that you correctly signed the CLA check. The issue that you hide your email in GitHub commits, so it shows up as `From: zach <40471358+orrefailaT@users.noreply.github.com>` instead of your real email address.

**Comment by pquentin** [comment]
Closing as the correct CLA was not signed. Please open a new pull request if you're OK to open a pull request with your real email. Thanks!

**Pull request closed without merging**
